CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS bureau_db;
CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS loan_db;
CREATE DATABASE IF NOT EXISTS bre_db;
CREATE DATABASE IF NOT EXISTS hunter_db;