version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - core-network
    container_name: zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    restart: always
  kafka:
    image: wurstmeister/kafka
    networks:
      - core-network
    container_name: kafka
    links:
      - zookeeper:zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "transaction.notification"
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - zookeeper
  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - core-network
    ports:
      - "3306:3306"
    volumes:
      - ../../init:/docker-entrypoint-initdb.d
      - mysqldb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - core-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
     - "27017:27017"
    volumes:
    - mongodb_data:/data/db
  redis:
    image: redis
    container_name: redis
    networks:
      - core-network
    ports:
    - "6379:6379"
    volumes:
    - redis_data:/data
  vault:
    image: vault:1.13.2
    container_name: vault
    networks:
      - core-network
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "vOU1OCs0IDS6pjr6xGKgkq9AVWhCrs4fo5dVvuK3UDk"
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - "vault-logs:/vault/logs"
      - "vault-file:/vault/file"
networks:
  core-network:
    driver: bridge
volumes:
  mysqldb_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  vault-logs:
    driver: local
  vault-file:
    driver: local
