server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: loan-orchestration
          uri: lb://loan-orchestration
          predicates:
            - Path=/api/v1/leads/**
          filters: AuthenticationFilter
        - id: hunter-service
          uri: lb://hunter-service
          predicates:
            - Path=/api/v1/hunter/**
          filters: AuthenticationFilter
        - id: bureau-service
          uri: lb://bureau-service
          predicates:
            - Path=/api/v1/bureau/**
          filters: AuthenticationFilter
        - id: bre-service
          uri: lb://bre-service
          predicates:
            - Path=/api/v1/bre/**
          filters: AuthenticationFilter
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters: AuthenticationFilter
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**
          filters: AuthenticationFilter
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/auth/**
          filters: AuthenticationFilter
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**
          filters: AuthenticationFilter
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters: AuthenticationFilter
