server:
  port: 8095
spring:
  application:
    name: hunter-service
    version: 1.0
  datasource:
    url: jdbc:mysql://mysql:3306/hunter_db
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  config:
#    import: configserver:http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"