spring:
  application:
    name: loan-orchestration
  config:
    import: configserver:http://config-server:8888
  profiles:
    active:
      - uat
#  cloud:
#    vault:
#      kv:
#        enabled: true
#        application-name: loan-orchestration
#      authentication: TOKEN
#      token: vOU1OCs0IDS6pjr6xGKgkq9AVWhCrs4fo5dVvuK3UDk
#      scheme: http
#      uri: http://vault:8200
#    config:
#      import: vault://
