server:
  port: 8096
spring:
  application:
    name: loan-orchestration
    version: 1.0
  profiles:
    active:
      - local
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loan_db?autoReconnect=true&useSSL=false
    #url: jdbc:mysql://mysql:3306/loan_db?autoReconnect=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect